---
# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: localhost webApp
    port: 4200
    onOpen: open-browser
    visibility: public
  - name: GitPod
    port: 5900
    onOpen: ignore
    visibility: public
  - name: GitPod
    port: 6080
    onOpen: ignore
    visibility: public

# Tarefas na Inicialização
tasks:
  - name: Setup, Install
    before: export NG_CLI_ANALYTICS=ci
    init: echo n | npm i -g @angular/cli@13.2.0
    command: cd crud-angular && npm ci && npm run start
