# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: localhost webApp
    port: 4200
    onOpen: open-browser
    visibility: public
  - name: localhost api
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: localhost api
    port: 8080
    onOpen: open-preview
    visibility: public
  - name: Testes Karma
    port: 9222
    onOpen: ignore
    visibility: public
  - name: Testes Karma
    port: 9876
    onOpen: ignore
    visibility: public


# Tarefas na Inicialização
tasks:
  - name: Start front-end
    before: export NG_CLI_ANALYTICS=ci
    init: echo n | npm i -g @angular/cli@17
    command: cd crud-angular && npm ci && npm run start
  - name: Start back-end
    before: export PATH=${PATH}:${MAVEN_HOME}/bin:${M2_HOME}/bin
    command: |
      mkdir /home/gitpod/.m2
      export DEV_ENVIRONMENT_HOST=`gp url 3000`
#      cd crud-spring && mvn exec:java
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - MohammadBaqer.better-folding
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-british-english
    - vscjava.vscode-java-debug
    - redhat.java
    - vscjava.vscode-maven
    - esbenp.prettier-vscode
    - vscjava.vscode-java-dependency
    - redhat.fabric8-analytics
    - humao.rest-client
    - hbenl.vscode-jasmine-test-adapter
    - ms-vscode.live-server
    - PKief.material-icon-theme
    - vscjava.vscode-spring-boot-dashboard
    - vmware.vscode-spring-boot
    - vscjava.vscode-spring-initializr
    - hbenl.test-adapter-converter
    - hbenl.vscode-test-explorer
    - vscjava.vscode-java-test
